version: "3"
services:
  backend:
    build: .
    restart: always
    ports: 
      - 8080:8080
    depends_on:
      - redis
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
    ports:
      - 6379:6379